# Exclude Dependencies
excluded:
  - Carthage

# Rules
line_length: 120

disabled_rules:
  - block_based_kvo

cyclomatic_complexity:
  warning: 3
  error: 5
  ignores_case_statements: true

vertical_whitespace:
  max_empty_lines: 2

